--CREATING TABLE
CREATE TABLE A(ID int);

INSERT INTO A 
VALUES (1),(1),(1),(2),(2),(NULL),(3),(4),(NULL),(NULL);

CREATE TABLE B(ID int);
INSERT INTO B
VALUES (1),(1),(2),(2),(2),(3),(3),(NULL),(4),(NULL),(NULL),(5),(5);
